

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["BackEnd/BackEnd.csproj", "./"]
COPY ["FrontEnd/FrontEnd.csproj", "./"]
COPY ["Login/Login.csproj", "./"]


COPY . .
WORKDIR "/src/BackEnd"

