FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_URLS=http://+:80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY BackEnd .
WORKDIR "/src"
RUN dotnet restore
RUN dotnet build "BackEnd.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BackEnd.csproj" -c Release -o /app/publish

FROM base AS final

WORKDIR /app
COPY BackEnd/Resources .
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BackEnd.dll"]