FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR "/src/BackEnd"
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_URLS=http://+:80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY . .
WORKDIR "/src/BackEnd"
RUN dotnet restore
RUN dotnet build "BackEnd.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BackEnd.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR "/src/BackEnd"
COPY --from=publish /src/publish .
ENTRYPOINT ["dotnet", "BackEnd.dll"]